config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'users/show'
  get 'users/index'
  get :signup,       to: 'users#new'
  resources :users
  resources :dishes
  root 'static_pages#home'
  get :about,        to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :name, presence: true, length: { maximum: 30 }
  validates :description, length: { maximum: 140 }
  validates :tips, length: { maximum: 50 }
  validates :popularity,
            :numericality => {
              :only_interger => true,
              :greater_than_or_equal_to => 1,
              :less_than_or_equal_to => 5
            },
            allow_nil: true
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:edit, :update]

  def new
    @dish = Dish.new
  end
    
  def show
    @dish = Dish.find(params[:id])
  end
  
  def create
    @dish = current_user.dishes.build(dish_params)
    if @dish.save
      flash[:success] = "料理が登録されました！"
      redirect_to dish_path(@dish)
    else
      render 'dishes/new'
    end
  end
  
  def edit
    @dish = Dish.find(params[:id])
  end

  def update
    @dish = Dish.find(params[:id])
    if @dish.update_attributes(dish_params)
      flash[:success] = "料理情報が更新されました！"
      redirect_to @dish
    else
      render 'edit'
    end
  end
  
  def destroy
    @dish = Dish.find(params[:id])
    if current_user.admin? || current_user?(@dish.user)
      @dish.destroy
      flash[:success] = "料理が削除されました"
      redirect_to request.referrer == user_url(@dish.user) ? user_url(@dish.user) : root_url
    else
      flash[:danger] = "他人の料理は削除できません"
      redirect_to root_url
    end
  end
  
  private

    def dish_params
      params.require(:dish).permit(:name, :discription, :portion, :tips,
                                   :reference, :required_time, :popularity, :cook_memo)
    end
    
    def correct_user
      # 現在のユーザーが更新対象の料理を保有しているかどうか確認
      @dish = current_user.dishes.find_by(id: params[:id])
      redirect_to root_url if @dish.nil?
    end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_dish.html.erb
<li id="dish-<%= dish.id %>">
  <%= link_to gravatar_for(dish.user, size: 50), dish.user %>
  <span class="name"><%= link_to dish.name, dish_path(dish) %></span>
  <span class="description"><%= dish.description %></span><br>
  <span class="required_time">所要時間：<%= dish.required_time %>分　</span>
  <span class="popularity">人気度：<%= dish.popularity %></span><br>
  <span class="reference"><%= link_to "作り方", dish.reference, target: :_blank %></span>
  <span class="timestamp">
    <%= time_ago_in_words(dish.created_at) %>前に投稿
  </span>
  <% if current_user.admin? || (current_user == dish.user) %>
    <%= link_to "削除", dish_path(dish), method: :delete,
                       data: { confirm: "本当に削除しますか？" } %>
  <% end %>
</li>

app/views/dishes/_dish_form.html.erb
<%= form_with model: @dish, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class = 'form-group'>
    <%= f.label :name %>　<span class="input-need">※必須</span>
    <%= f.text_field :name, class: 'form-control', id: 'dish_name' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :description %>　<span class="input-unneed">※任意</span>
    <%= f.text_field :description, size: "60x4", class: 'form-control', id: 'dish_description' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :portion %> [分量]　<span class="input-unneed">※任意</span>
    <%= f.text_field :portion, class: 'form-control', id: 'dish_portion' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :tips %>　<span class="input-unneed">※任意</span>
    <%= f.text_field :tips, size: "30x4", class: 'form-control', id: 'dish_tips' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :reference %>　<span class="input-unneed">※任意</span>
    <%= f.text_field :reference, class: 'form-control', id: 'dish_reference' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :required_time %> [分]　<span class="input-unneed">※任意</span>
    <%= f.text_field :required_time, class: 'form-control', id: 'dish_required_time' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :popularity %> [1~5]　<span class="input-unneed">※任意</span>
    <%= f.text_field :popularity, class: 'form-control', id: 'dish_popularity' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :cook_memo %>　<span class="input-unneed">※任意</span>
    <%= f.text_field :cook_memo, class: 'form-control', id: 'dish_cook_memo' %>
  </div>
  <%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/dishes/edit.html.erb
<% provide(:title, "料理情報の編集") %>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@dish) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class = 'form-group'>
          <%= f.label :name %>　<span class="input-need">※必須</span>
          <%= f.text_field :name, class: 'form-control', id: 'dish_name' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :description %>　<span class="input-unneed">※任意</span>
          <%= f.text_field :description, size: "60x4", class: 'form-control', id: 'dish_description' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :portion %> [人分]　<span class="input-unneed">※任意</span>
          <%= f.text_field :portion, class: 'form-control', id: 'dish_portion' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :tips %>　<span class="input-unneed">※任意</span>
          <%= f.text_field :tips, size: "30x4", class: 'form-control', id: 'dish_tips' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :reference %>　<span class="input-unneed">※任意</span>
          <%= f.text_field :reference, class: 'form-control', id: 'dish_reference' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :required_time %> [分]　<span class="input-unneed">※任意</span>
          <%= f.text_field :required_time, class: 'form-control', id: 'dish_required_time' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :popularity %> [1~5]　<span class="input-unneed">※任意</span>
          <%= f.text_field :popularity, class: 'form-control', id: 'dish_popularity' %>
        </div>
        <%= f.submit "更新する", class: "btn btn-primary" %>
        <p></p>
        <%= link_to "料理を削除する", dish_path(@dish), method: :delete,
                                   data: { confirm: "本当にこの料理を削除してよろしいですか？" } %>
      <% end %>
    </div>
  </div>
</div>

app/views/dishes/new.html.erb
<% provide(:title, "料理登録") %>
<div class="container">
  <h1>料理登録</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'dishes/dish_form' %>
    </div>
  </div>
</div>

app/views/dishes/show.html.erb
<% provide(:title, "#{@dish.name}") %>
<div class="container">
  <div class="row">
   <h2 class="dish-name"><%= @dish.name %></h2>
    <div class="change-dish">
      <% if current_user == @dish.user %>
        <%= link_to "編集", edit_dish_path(@dish), class: 'edit-dish' %>　
      <% end %>
      <% if current_user.admin? || (current_user == @dish.user) %>
        <%= link_to "削除", dish_path(@dish), method: :delete, class: 'delete-dish',
                                      data: { confirm: "本当に削除しますか？" } %>
      <% end %>
    </div>
    <h4><%= @dish.description %></h4>
    <h4 class="dish-reference">作り方：<%= link_to "#{@dish.reference}", @dish.reference, target: "_blank" %></h4>
    <h4 class="dish-portion">分量：<%= @dish.portion %> 人分</h4>
    <div class="tips">
      <h5 class="title-tips">コツ・ポイント</h5>
      <h5><%= @dish.tips %></h5>
    </div>
    <div class="show-dish-other-info">
      <div class="dish-info">
        <h5>所要時間：</h5><h4><%= @dish.required_time %></h4> <h5>分</h5>
      </div>
      <div class="dish-info">
        <h5>人気度：</h5><h4><%= @dish.popularity %></h4>
      </div>
    </div>
  </div>
</div>